version: '3.3'

services:
  postgres_service:
    container_name: practice-postgres
    image: kartoza/postgis:14-3.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=fred
      - POSTGRES_DBNAME=todo_app
    ports:
      - 5432:5432

  zookeeper:
    image: zookeeper:latest
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_TICK_TIME: 2000
      ZOO_MAX_CLIENT_CNXNS: 10
      ZOO_MY_ID: 1
    networks:
      - todo-prac
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    depends_on:
      - zookeeper
    networks:
      - todo-prac
    links:
      - zookeeper:zk
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_MESSAGE_MAX_BYTES: 2000000
    
  elasticsearch:
    image: elasticsearch:7.16.2
    command: bin/elasticsearch -Expack.security.enabled=false -Ediscovery.type=single-node
    networks:
      - todo-prac
    ports:
      - "9200:9200"

networks:
  todo-prac:
